### ISSUE TITLE
"old phantom inventory" on closing window 99

### ISSUE THREAD

**Issue by HoverEpic** [WolverinDEV/BungeeUtil#6]
To reproduce, here is my tests:
- setup a fresh Bungeecord (with BungeeUtil 1.6.7.15) / spigot network
- log into Bungeecord
- gave you dirt (the dirt appear at slot 0)
- move the dirt in your bar (slot 3 for example)
- chat "bu" for testing inv (the dirt is still slot 3)
- close the menu with Esc (the dirt move to slot 0)
- open your inv, click on slot 0, the dirt return to slot 3

[Spigot post](https://www.spigotmc.org/threads/bungeeutil.74257/page-12#post-1982759)

**Comment by WolverinDEV** [comment]
Thank you :-1:
I will fix this as soon its possiable

**Comment by WolverinDEV** [comment]
Fixed here:
https://github.com/WolverinDEV/BungeeUtil/commit/bb3053359db35b91536acab86c991f0adc2f9e5a

**Comment by WolverinDEV** [comment]
I recived the message that this bug isnt fixed

**Comment by WolverinDEV** [comment]
Bug fixed. (I understand the new issue wrong)

**Comment by HoverEpic** [comment]
The problem is still present on 2.0, i have take a look and inventories actions are very difficult to handle ><
I think i'll just add the possibility to disable inventory storing in BungeeUtil with a boolean in conf (i'll probably make a PR for that if you are interested).

**Comment by WolverinDEV** [comment]
Its only in creative mode. In survival all is fixed but in creative the client dosnt send changes

**Comment by HoverEpic** [comment]
I'have found the origin of the problème, BUKKIT CHESTS!
(MainPacketHandler.java line 326 need +10)
Ive tested the solution with chests and bukkit generated menu, works fine.
#12

**Comment by HoverEpic** [comment]
#12

**Comment by WolverinDEV** [comment]
Okey i will test it but its sound plausible but i dont understand why 10?
9 is one row and where is the tenth slot? Do you know it?

**Comment by WolverinDEV** [comment]
Ahh okey i think i know why it should be ten :D

<an array>.length starts couting from 1 and not from zero like inventory slots.

**Comment by WolverinDEV** [comment]
I fixed this issue with the item shifting :)

**Comment by WolverinDEV** [comment]
Im fucking stupid....
https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/dev/wolveringer/bungeeutil/packetlib/handler/MainPacketHandler.java#L340
Forget to replace the number with the variable...
Need to change and test again... tomorrow....

**Comment by WolverinDEV** [comment]
Fixed here https://github.com/WolverinDEV/BungeeUtil/commit/1fcf1a87b745dd2032f7ce50a8e5251a112b4dac
Fucking yeah :D
